function LPC_Tool_GUI
% LPC_TOOL_GUI Load Profile Calculation Tool
% The tool opens a graphical user interface (GUI), with the GUI the user
% can set up all nessesary parameters for a power flow calculation with
% load profiles in Sincal. The PFC is controlled and started with the
% Matlab function Mat2Sin_LPCalc.
%
% Author(s): R. Brandalik
%            P. Gassler
%            J. Greiner
%            H. Kreten
%
% Contact: brandalikrobert@gmail.com, brandalik@eit.uni-kl.de
%
% Special thanks go to the entire TUK ESEM team.
%
% Parts of the work were the result of the project CheapFlex, sponsored by
% the German Federal Ministry of Economic Affairs and Energy as part of the
% 6th Energy Research Programme of the German Federal Government.

%% Check if the GUI is already opened

if ishandle(findobj('type','figure','Tag','LPC_Tool'))
    figure(findobj('type','figure','Tag','LPC_Tool'))
    return
    % close(figure(findobj('type','figure','Tag','LPC_Tool'))) % TODO (Temporary)
end

%% Definition of default global Settings
f           = struct;
f.Inputs    = struct;

f.Inputs.Data_Path      = [pwd,'\Data\'                         ];
f.Inputs.Inputs_Path    = [pwd,'\Inputs\'                       ];
f.Inputs.Outputs_Path   = [pwd,'\Outputs\'                      ];
f.Inputs.Grid_Path      = [pwd,'\Inputs\Grids\'                 ];
f.Inputs.LP_DB_Path     = [pwd,'\Inputs\Load_Profiles\'         ];
f.Inputs.LP_dist_path   = [pwd,'\Inputs\Profiles_Distribution\' ];
f.Inputs.PV_dist_path   = [pwd,'\Inputs\Profiles_Distribution\' ];
f.Inputs.PV_DB_Path     = [pwd,'\Inputs\PV_Profiles\'           ];

% TODO: No function yet.
% f.Inputs.TimeSetup_First_Moment    = datetime('01.01.2015 00:00:00', 'Format', 'dd.MM.yyyy HH:mm:ss');
% f.Inputs.TimeSetup_Last_Moment     = datetime('31.12.2015 23:50:00', 'Format', 'dd.MM.yyyy HH:mm:ss');
% f.Inputs.TimeSetup_First_Moment_PF = datetime('01.01.2015 00:00:00', 'Format', 'dd.MM.yyyy HH:mm:ss');
% f.Inputs.TimeSetup_Last_Moment_PF  = datetime('01.01.2015 00:00:00', 'Format', 'dd.MM.yyyy HH:mm:ss');
% f.Inputs.TimeSetup_Time_Step       = 10;      % Minutes
% f.Inputs.TimeSetup_num_of_instants = 52560;

%% Check Sincal Version and corresponding 'Sincal.Simulation' connection
max_Version_Sincal  = 14;
max_Version_Mat2Sin = 11;
VersionInstalled = false;
while ~VersionInstalled
    try
        actxserver(['Sincal.Simulation.',num2str(max_Version_Mat2Sin)]);
        VersionInstalled = true;
        clear ans
    catch
        max_Version_Sincal  = max_Version_Sincal  - 0.5  ;
        max_Version_Mat2Sin = max_Version_Mat2Sin - 1    ;
    end
    if max_Version_Sincal < 0; disp('Sincal is not installed.\n'); return; end
end

%% Check number of posible Cores for Parallel computing
myCluster = parcluster('local');
f.max_num_Workers = myCluster.NumWorkers;

%% Define colors for GUI
Colors.mW       = [0.92 0.92 0.92]; % mW - main Window
Colors.pb       = [1.0  1.0  1.0 ]; % pb - pushbutton
Colots.pm       = [1.0  1.0  1.0 ]; % pm - popupmenu
Colors.et       = [1.0  1.0  1.0 ]; % ed - edit text
Colors.panel_fg = [1.0  0.1  0.8 ]; % fg - ForegroundColor
Colors.panel_sc = [0.2  0.2  0.2 ]; % sc - ShadowColor

%% Define font size for GUI
Fontsz.units  = 'pixels';       % TODO: In the future maybe with 'normalized'
Fontsz.title  = 32;
Fontsz.panels = 15;
Fontsz.basic  = 12;
Fontsz.small  = 10;

%% Definition of Main Window
f.Main_Win.figure = ...
    figure(...
    'Name'          , 'LPC Tool'                ,...
    'NumberTitle'   , 'off'                     ,...
    'Tag'           , 'LPC_Tool'                ,...
    'Toolbar'       , 'none'                    ,...
    'MenuBar'       , 'none'                    ,...
    'Visible'       , 'off'                     ,...
    'Resize'        , 'on'                      ,...
    'Color'         , Colors.mW                 ,...
    'Units'         , 'normalized'              ,...
    'Position'      , [0.256 0.277 0.521 0.630]  ...
    );

f.Main_Win.text_Title = ...
    uicontrol(f.Main_Win.figure                                     ,...
    'Style'                 , 'text'                                ,...
    'Units'                 , 'normalized'                          ,...
    'Position'              , [0.0 0.93 1.0 0.06]                   ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color               ,...
    'String'                , 'Load Profile Calculation (PLC) Tool' ,...
    'HorizontalAlignment'   , 'center'                              ,...
    'FontUnits'             , Fontsz.units                          ,...
    'ForegroundColor'       , Colors.panel_fg                       ,...
    'FontSize'              , Fontsz.title                           ...
    );

%% Main Window subpanels
f.Main_Win.uipanel_input = ...
    uipanel(f.Main_Win.figure                       ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.01 0.01 0.48 0.9]      ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Input data'              ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'centertop'               ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledout'               ...
    );

f.Main_Win.uipanel_output = ...
    uipanel(f.Main_Win.figure                       ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.51 0.33 0.48 0.58]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Output data'             ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'centertop'               ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledout'               ...
    );

f.Main_Win.uipanel_control = ...
    uipanel(f.Main_Win.figure                       ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.51 0.01 0.48 0.32]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Power Flow control'      ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'centertop'               ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledout'               ...
    );

%% Input data subpanels
f.Main_Win.uipanel_input_grid = ...
    uipanel(f.Main_Win.uipanel_input                ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.80 0.96 0.20]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Grid selection'          ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

f.Main_Win.uipanel_input_LP = ...
    uipanel(f.Main_Win.uipanel_input                ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.48 0.96 0.32]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Load Profiles'           ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

f.Main_Win.uipanel_input_PV = ...
    uipanel(f.Main_Win.uipanel_input                ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.16 0.96 0.32]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'PV Profiles'             ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

f.Main_Win.uipanel_general = ...
    uipanel(f.Main_Win.uipanel_input                ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.02 0.96 0.14]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'General'                 ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

%% Input data load profiles subpanels
f.Main_Win.uibuttongroup_input_LP_DB_Type = ...
    uibuttongroup(f.Main_Win.uipanel_input_LP           ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.52 0.96 0.48]         ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Title'             , 'Select Load Profile type'    ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'TitlePosition'     , 'centertop'                   ,...
    'ForegroundColor'   , Colors.panel_fg               ,...
    'ShadowColor'       , Colors.panel_sc               ,...
    'BorderWidth'       , 2                             ,...
    'BorderType'        , 'beveledout'                   ...
    );

f.Main_Win.uibuttongroup_input_LP_dist = ...
    uibuttongroup(f.Main_Win.uipanel_input_LP                   ,...
    'Units'             , 'normalized'                          ,...
    'Position'          , [0.02 0.02 0.96 0.48]                 ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color               ,...
    'Title'             , 'Select Load Profile distribution'    ,...
    'FontUnits'         , Fontsz.units                          ,...
    'FontSize'          , Fontsz.basic                          ,...
    'TitlePosition'     , 'centertop'                           ,...
    'ForegroundColor'   , Colors.panel_fg                       ,...
    'ShadowColor'       , Colors.panel_sc                       ,...
    'BorderWidth'       , 2                                     ,...
    'BorderType'        , 'beveledout'                          ...
    );

%% Input data PV profiles subpanels
f.Main_Win.uibuttongroup_input_PV_DB_Type = ...
    uibuttongroup(f.Main_Win.uipanel_input_PV       ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.52 0.96 0.48]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Select PV Profile type'  ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic              ,...
    'TitlePosition'     , 'centertop'               ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         , ...
    'BorderType'        , 'beveledout'              ...
    );

f.Main_Win.uibuttongroup_input_PV_dist = ...
    uibuttongroup(f.Main_Win.uipanel_input_PV               ,...
    'Units'             , 'normalized'                      ,...
    'Position'          , [0.02 0.02 0.96 0.48]             ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color           ,...
    'Title'             , 'Select PV Profile distribution'  ,...
    'FontUnits'         , Fontsz.units                      ,...
    'FontSize'          , Fontsz.basic                      ,...
    'TitlePosition'     , 'centertop'                       ,...
    'ForegroundColor'   , Colors.panel_fg                   ,...
    'ShadowColor'       , Colors.panel_sc                   ,...
    'BorderWidth'       , 2                                 ,...
    'BorderType'        , 'beveledout'                       ...
    );

%% Output data subpanels
f.Main_Win.uipanel_output_data_selection = ...
    uipanel(f.Main_Win.uipanel_output               ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.40 0.96 0.32]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'          	, 'Select output data'      ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

f.Main_Win.uipanel_output_path_selection = ...
    uipanel(f.Main_Win.uipanel_output               ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.02 0.96 0.36]     ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Title'             , 'Select output path'      ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.panels             ,...
    'FontWeight'        , 'bold'                    ,...
    'TitlePosition'     , 'lefttop'                 ,...
    'ForegroundColor'   , Colors.panel_fg           ,...
    'ShadowColor'       , Colors.panel_sc           ,...
    'BorderWidth'       , 2                         ,...
    'BorderType'        , 'beveledin'                ...
    );

%% Input data grid section panel
f.Main_Win.pushbutton_grid_path = ...
    uicontrol(f.Main_Win.uipanel_input_grid         ,...
    'Style'             , 'pushbutton'              ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.02 0.72 0.28 0.22]     ,...
    'Backgroundcolor'   , Colors.pb                 ,...
    'String'            , 'Change Folder'           ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic               ...
    );

f.Main_Win.text_grid_path = ...
    uicontrol(f.Main_Win.uipanel_input_grid             ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.02 0.41 0.9 0.28]      ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color   ,...
    'String'                , f.Inputs.Grid_Path        ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.small               ...
    );

f.Main_Win.popupmenu_grid_selection = ...
    uicontrol(f.Main_Win.uipanel_input_grid     ,...
    'Style'             , 'popupmenu'           ,...
    'Units'             , 'normalized'          ,...
    'Position'          , [0.02 0.10 0.96 0.25] ,...
    'String'            , {'Select grid...'}    ,...
    'Value'             , 1                     ,...
    'BackgroundColor'   , Colots.pm             ,...
    'FontUnits'         , Fontsz.units          ,...
    'FontSize'          , Fontsz.basic           ...
    );

%% Input data load profiles select Load profile type panel
f.Main_Win.radiobutton_input_LP_DB = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_DB_Type ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.65 0.2 0.25]          ,...
    'String'            , 'Database'                    ,...
    'Enable'            , 'on'                          ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_LP_LZR_Tool = ...                  % TODO: No function yet!
    uicontrol(f.Main_Win.uibuttongroup_input_LP_DB_Type ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.22 0.65 0.2 0.25]          ,...
    'String'            , 'LZR Tool'                    ,...
    'Enable'            , 'off'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_LP_AAPD = ...                      % TODO: No function yet!
    uicontrol(f.Main_Win.uibuttongroup_input_LP_DB_Type ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.42 0.65 0.2 0.25]          ,...
    'String'            , 'AAPD'                        ,...
    'Enable'            , 'off'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.pushbutton_DB_LP_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_DB_Type ,...
    'Style'             , 'pushbutton'                  ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.14 0.28 0.35]         ,...
    'String'            , 'Choose File'                 ,...
    'BackgroundColor'   , Colors.pb                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Enable'            , 'on'                           ...
    );

f.Main_Win.edit_DB_LP_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_DB_Type                 ,...
    'Style'             , 'edit'                                        ,...
    'Units'             , 'normalized'                                  ,...
    'Position'          , [0.32 0.14 0.66 0.35]                         ,...
    'String'            , [f.Inputs.LP_DB_Path, 'IEEE_Lo_Profiles.mat'] ,...
    'Value'             , 1                                             ,...
    'BackgroundColor'   , Colors.et                                     ,...
    'FontUnits'         , Fontsz.units                                  ,...
    'FontSize'          , Fontsz.basic                                  ,...
    'Enable'            , 'on'                                         	 ...
    );

%% Input data load profiles select Load profile distribution panel
f.Main_Win.radiobutton_input_dist_LP_list = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.65 0.3 0.25]          ,...
    'String'            , 'Dist. List'                  ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ...
    );

f.Main_Win.radiobutton_input_dist_LP_random = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.22 0.65 0.2 0.25]          ,...
    'String'            , 'Random'                      ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_LP_DB_order = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.42 0.65 0.2 0.25]          ,...
    'String'            , 'DB order'                    ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.radiobutton_input_dist_LP_sort = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.62 0.65 0.2 0.25]          ,...
    'String'            , 'Alphabetic'                  ,...
    'Enable'            , 'on'                          ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_LP_manual = ...               % TODO: No function yet!
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.82 0.65 0.2 0.25]          ,...
    'String'            , 'Manual'                      ,...
    'Enable'            , 'off'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.pushbutton_dist_list_LP_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'pushbutton'                  ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.14 0.28 0.35]         ,...
    'String'            , 'Choose File'                 ,...
    'Value'             , 0                             ,...
    'BackgroundColor'	, Colors.pb                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Enable'            , 'off'                          ...
    );

f.Main_Win.edit_dist_list_LP_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_LP_dist    ,...
    'Style'             , 'edit'                        ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.32 0.14 0.66 0.35]         ,...
    'String'            , f.Inputs.LP_dist_path         ,...
    'Value'             , 1                             ,...
    'BackgroundColor'   , Colors.et                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Enable'            , 'off'                          ...
    );

%% Input data PV profiles select PV profile type panel
f.Main_Win.radiobutton_input_PV_DB = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_DB_Type ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.65 0.2 0.25]          ,...
    'String'            , 'Database'                    ,...
    'Enable'            , 'on'                          ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_PV_LZR_Tool = ...                  % TODO: No function yet!
    uicontrol(f.Main_Win.uibuttongroup_input_PV_DB_Type ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.22 0.65 0.2 0.25]          ,...
    'String'           	, 'LZR Tool'                    ,...
    'Enable'            , 'off'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.pushbutton_DB_PV_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_DB_Type ,...
    'Style'             , 'pushbutton'                  ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.14 0.28 0.35]         ,...
    'String'            , 'Choose File'                 ,...
    'Enable'            , 'on'                          ,...
    'BackgroundColor'   , Colors.pb                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.edit_DB_PV_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_DB_Type                 ,...
    'Style'             , 'edit'                                        ,...
    'Units'             , 'normalized'                                  ,...
    'Position'          , [0.32 0.14 0.66 0.35]                         ,...
    'String'            , [f.Inputs.PV_DB_Path, 'RB_PV_Profiles.mat']   ,...
    'Enable'            , 'on'                                          ,...
    'Value'             , 1                                             ,...
    'BackgroundColor'   , Colors.et                                     ,...
    'FontUnits'         , Fontsz.units                                  ,...
    'FontSize'          , Fontsz.basic                                   ...
    );

%% Input data PV profiles select PV profile distribution panel
f.Main_Win.radiobutton_input_dist_PV_list = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.65 0.3 0.25]          ,...
    'String'            , 'Dist. List'                  ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_PV_random = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.22 0.65 0.2 0.25]          ,...
    'String'            , 'Random'                      ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_PV_DB_order = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.42 0.65 0.2 0.25]          ,...
    'String'            , 'DB order'                    ,...
    'FontUnits'         , Fontsz.units                  ,...
    'Value'             , 1                             ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_PV_sort = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.62 0.65 0.2 0.25]          ,...
    'String'            , 'Alphabetic'                  ,...
    'Enable'            , 'on'                          ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.radiobutton_input_dist_PV_manual = ...               % TODO: No function yet!
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'radiobutton'                 ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.82 0.65 0.2 0.25]          ,...
    'String'            , 'Manual'                      ,...
    'Enable'            , 'off'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'       	, Fontsz.basic                   ...
    );

f.Main_Win.pushbutton_dist_list_PV_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'pushbutton'                  ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.14 0.28 0.35]         ,...
    'String'            , 'Choose File'                 ,...
    'Value'             , 0                             ,...
    'BackgroundColor' 	, Colors.pb                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'Enable'            , 'off'                         ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.edit_dist_list_PV_path = ...
    uicontrol(f.Main_Win.uibuttongroup_input_PV_dist    ,...
    'Style'             , 'edit'                        ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.32 0.14 0.66 0.35]         ,...
    'String'            , f.Inputs.PV_dist_path         ,...
    'Value'             , 1                             ,...
    'BackgroundColor'   , Colors.et                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'Enable'            , 'off'                         ,...
    'FontSize'          , Fontsz.basic                   ...
    );

%% Input data general panel
f.Main_Win.text_VerSincal = ...
    uicontrol(f.Main_Win.uipanel_general                ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.02 0.54 0.66 0.35]     ,...
    'String'                , 'Sincal Version:'         ,...
    'Backgroundcolor'   	, f.Main_Win.figure.Color   ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.basic               ...
    );

f.Main_Win.edit_VerSincal = ...
    uicontrol(f.Main_Win.uipanel_general                    ,...
    'Style'                 , 'edit'                        ,...
    'Units'                 , 'normalized'                  ,...
    'Position'              , [0.27 0.60 0.08 0.35]         ,...
    'String'                , num2str(max_Version_Sincal)   ,...
    'Backgroundcolor'       , Colors.et                     ,...
    'HorizontalAlignment'	, 'left'                        ,...
    'FontUnits'             , Fontsz.units                  ,...
    'FontSize'              , Fontsz.basic                   ...
    );

f.Main_Win.text_NumelTimestep = ...
    uicontrol(f.Main_Win.uipanel_general                ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.39 0.54 0.66 0.35]     ,...
    'String'                , 'No. Timestep:'           ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color   ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.basic               ...
    );

f.Main_Win.edit_NumelTimestep = ...                             % TODO: No function yet!
    uicontrol(f.Main_Win.uipanel_general            ,...
    'Style'                 , 'edit'                ,...
    'Units'                 , 'normalized'          ,...
    'Position'              , [0.57 0.60 0.12 0.35] ,...
    'String'                , 'max'                 ,...
    'Backgroundcolor'       , Colors.et             ,...
    'HorizontalAlignment'   , 'left'                ,...
    'FontUnits'             , Fontsz.units          ,...
    'Enable'                , 'off'                 ,...
    'FontSize'              , Fontsz.basic           ...
    );

f.Main_Win.text_ParrallelCom = ...
    uicontrol(f.Main_Win.uipanel_general                ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.02 0.10 0.66 0.35]     ,...
    'String'                , 'Parallel computing:'     ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color   ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.basic               ...
    );

f.Main_Win.popupmenu_ParrallelCom = ...
    uicontrol(f.Main_Win.uipanel_general        ,...
    'Style'             , 'popupmenu'           ,...
    'Units'             , 'normalized'          ,...
    'Position'          , [0.27 0.05 0.10 0.45] ,...
    'String'            , {'Yes', 'No'}         ,...
    'Value'             , 1                     ,...
    'BackgroundColor'   , Colots.pm             ,...
    'FontUnits'         , Fontsz.units          ,...
    'FontSize'          , Fontsz.basic           ...
    );

f.Main_Win.text_NumelCores = ...
    uicontrol(f.Main_Win.uipanel_general                ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.39 0.10 0.66 0.35]     ,...
    'String'                , 'No. Cores:'              ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color   ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.basic               ...
    );

f.Main_Win.popupmenu_NumelCores = ...
    uicontrol(f.Main_Win.uipanel_general            ,...
    'Style'             , 'popupmenu'               ,...
    'Units'             , 'normalized'              ,...
    'Position'          , [0.57 0.05 0.09 0.45]     ,...
    'String'            , {1 : f.max_num_Workers}   ,...
    'Value'             , f.max_num_Workers - 1   	,...
    'BackgroundColor'   , Colots.pm                 ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic               ...
    );

f.Main_Win.text_NumelCores_max = ...
    uicontrol(f.Main_Win.uipanel_general                            ,...
    'Style'                 , 'text'                                ,...
    'Units'                 , 'normalized'                          ,...
    'Position'              , [0.67 0.10 0.66 0.35]                 ,...
    'String'                , ['max: ',num2str(f.max_num_Workers)] 	,...
    'Backgroundcolor'       , f.Main_Win.figure.Color               ,...
    'HorizontalAlignment'   , 'left'                                ,...
    'FontUnits'             , Fontsz.units                          ,...
    'FontSize'              , Fontsz.basic                          ,...
    'FontAngle'             , 'italic'                               ...
    );

%% Output data panel
f.Main_Win.checkbox_output_active = ...
    uicontrol(f.Main_Win.uipanel_output             ,...
    'Style'             , 'checkbox'                ,...
    'Units'             , 'normalized'              ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Position'          , [0.02 0.9 0.35 0.1]       ,...
    'String'            , 'Activate Output'         ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic              ,...
    'Value'             , 1                          ...
    );

f.Main_Win.checkbox_output_raw_only = ...
    uicontrol(f.Main_Win.uipanel_output                     ,...
    'Style'             , 'checkbox'                        ,...
    'Units'             , 'normalized'                      ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color           ,...
    'Position'          , [0.3 0.9 0.45 0.1]                ,...
    'String'            , 'Output RAW data only (faster)'   ,...
    'FontUnits'         , Fontsz.units                      ,...
    'FontSize'          , Fontsz.basic                      ,...
    'Value'             , 0                                  ...
    );

f.Main_Win.checkbox_output_raw = ...
    uicontrol(f.Main_Win.uipanel_output             ,...
    'Style'             , 'checkbox'                ,...
    'Units'             , 'normalized'              ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Position'          , [0.70 0.9 0.45 0.1]       ,...
    'String'            , 'RAW data'                ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic              ,...
    'Value'             , 0                          ...
    );

f.Main_Win.checkbox_output_data_selection_delete_temp_files = ...
    uicontrol(f.Main_Win.uipanel_output             ,...
    'Style'             , 'checkbox'            	,...
    'Units'             , 'normalized'              ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color   ,...
    'Position'          , [0.02 0.82 0.45 0.1]      ,...
    'String'            , 'Delete temp files'       ,...
    'FontUnits'         , Fontsz.units              ,...
    'FontSize'          , Fontsz.basic              ,...
    'Value'             , 1                          ...
    );

f.Main_Win.pushbutton_generate_output = ...                     % TODO: No function yet!
    uicontrol(f.Main_Win.uipanel_output             ,...
    'Style'             , 'pushbutton'              ,...
    'Units'             , 'normalized'              ,...
    'Backgroundcolor'   , Colors.pb                 ,...
    'Position'          , [0.02 0.74 0.28 0.06]     ,...
    'String'            , 'Generate Output Only' 	,...
    'FontUnits'         , Fontsz.units              ,...
    'Enable'            , 'off'                     ,...
    'FontSize'          , Fontsz.basic              ,...
    'Value'             , 0                          ...
    );

%% Output data select output data panel
f.Main_Win.checkbox_output_data_selection_U = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.7 0.1 0.2]            ,...
    'String'            , 'U'                           ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_P = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.13 0.7 0.1 0.2]            ,...
    'String'            , 'P'                           ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_Q = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.28 0.7 0.1 0.2]            ,...
    'String'            , 'Q'                           ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_S = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.43 0.7 0.1 0.2]            ,...
    'String'            , 'S'                           ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_Phi = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.59 0.7 0.1 0.2]            ,...
    'String'            , 'Phi'                         ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_Sin_Info = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.73 0.7 0.3 0.2]            ,...
    'String'            , 'SinInfo'                     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_I = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.45 0.1 0.2]           ,...
    'String'            , 'I'                           ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_P_flow = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.13 0.45 0.2 0.2]           ,...
    'String'            , 'P_flow'                      ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_Q_flow = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.28 0.45 0.2 0.2]           ,...
    'String'            , 'Q_flow'                      ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_S_flow = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.43 0.45 0.2 0.2]           ,...
    'String'            , 'S_flow'                      ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_T_Vector = ...            % TODO: No function yet!
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.73 0.45 0.3 0.2]           ,...
    'String'            , 'TimeVector'                  ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 0                             ,...
    'Enable'            , 'off'                          ...
    );

f.Main_Win.checkbox_output_data_selection_per_unit = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.02 0.18 0.4 0.2]           ,...
    'String'            , 'Results per Unit'            ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

f.Main_Win.checkbox_output_data_selection_per_node_branch = ...
    uicontrol(f.Main_Win.uipanel_output_data_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'Position'          , [0.28 0.18 0.6 0.2]           ,...
    'String'            , 'Results per Node/Branch'     ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                  ,...
    'Value'             , 1                              ...
    );

%% Output data select output path panel
f.Main_Win.pushbutton_output_path_selection = ...
    uicontrol(f.Main_Win.uipanel_output_path_selection  ,...
    'Style'             , 'pushbutton'                  ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.78 0.3 0.18]          ,...
    'Backgroundcolor'   , Colors.pb                     ,...
    'String'            , 'Change Folder'               ,...
    'FontUnits'         , Fontsz.units                  ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.text_output_path_selection = ...
    uicontrol(f.Main_Win.uipanel_output_path_selection  ,...
    'Style'                 , 'text'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.02 0.50 0.96 0.25]     ,...
    'Backgroundcolor'       , f.Main_Win.figure.Color   ,...
    'String'                , f.Inputs.Outputs_Path     ,...
    'Value'                 , 1                         ,...
    'FontUnits'             , Fontsz.units              ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontSize'              , Fontsz.small               ...
    );

f.Main_Win.checkbox_output_path_filename = ...
    uicontrol(f.Main_Win.uipanel_output_path_selection  ,...
    'Style'             , 'checkbox'                    ,...
    'Units'             , 'normalized'                  ,...
    'Position'          , [0.02 0.3 0.3 0.15]           ,...
    'String'            , 'Default filename'            ,...
    'Backgroundcolor'   , f.Main_Win.figure.Color       ,...
    'FontUnits'         , Fontsz.units                  ,...
    'Value'             , 1                             ,...
    'FontSize'          , Fontsz.basic                   ...
    );

f.Main_Win.edit_output_path_filename = ...
    uicontrol(f.Main_Win.uipanel_output_path_selection  ,...
    'Style'                 , 'edit'                    ,...
    'Units'                 , 'normalized'              ,...
    'Position'              , [0.02 0.10 0.96 0.18]     ,...
    'Backgroundcolor'       , Colors.et                 ,...
    'String'                , 'Default filename'        ,...
    'Enable'                , 'off'                     ,...
    'HorizontalAlignment'   , 'left'                    ,...
    'FontUnits'             , Fontsz.units              ,...
    'FontSize'              , Fontsz.basic               ...
    );

%% Power flow control panel
f.Main_Win.pushbutton_start_PF = ...
    uicontrol(f.Main_Win.uipanel_control                    ,...
    'Style'             , 'pushbutton'                      ,...
    'Units'             , 'normalized'                      ,...
    'Position'          , [0.3 0.75 0.4 0.2]                ,...
    'Backgroundcolor'   , Colors.pb                         ,...
    'String'            , 'Start Power Flow calculation'    ,...
    'FontUnits'         , Fontsz.units                      ,...
    'FontSize'          , Fontsz.basic                       ...
    );

%% Fill menu with content

fill_menu_grid_selection(f)

%% Main Window visible

f.Main_Win.figure.Visible = 'on';

%% Pixels -> Normalized

Main_Win_fields = fields(f.Main_Win);   % Normalize parts -> TODO in future
for k = 1 : numel(Main_Win_fields)
    try
        f.Main_Win.(Main_Win_fields{k}).FontUnits = 'normalized';
    catch
    end
end

%% Definition of callback functions

% Callbacks for Grid selection
set(f.Main_Win.pushbutton_grid_path               , 'Callback',{@SelectGridPath       ,f});
set(f.Main_Win.popupmenu_grid_selection           , 'Callback',{@SelectGrid           ,f});
% Callbacks for Load Profil type and database selection
set(f.Main_Win.radiobutton_input_LP_DB            , 'Callback',{@SelectLP_DB_Type     ,f});
set(f.Main_Win.radiobutton_input_LP_LZR_Tool      , 'Callback',{@SelectLP_DB_Type     ,f});
set(f.Main_Win.radiobutton_input_LP_AAPD          , 'Callback',{@SelectLP_DB_Type     ,f});
set(f.Main_Win.pushbutton_DB_LP_path              , 'Callback',{@SelectLP_DB          ,f});
% Callbacks for radiobuttons LP distrubution
set(f.Main_Win.radiobutton_input_dist_LP_list     , 'Callback',{@SelectLP_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_LP_random   , 'Callback',{@SelectLP_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_LP_DB_order , 'Callback',{@SelectLP_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_LP_sort     , 'Callback',{@SelectLP_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_LP_manual   , 'Callback',{@SelectLP_dist_type   ,f});
set(f.Main_Win.pushbutton_dist_list_LP_path       , 'Callback',{@SelectLP_dist_list   ,f});
set(f.Main_Win.edit_dist_list_LP_path             , 'Callback',{@SelectLP_dist_list   ,f});
% Callbacks for PV Profile type and database selecetion
set(f.Main_Win.radiobutton_input_PV_DB            , 'Callback',{@SelectPV_DB_Type     ,f});
set(f.Main_Win.radiobutton_input_PV_LZR_Tool      , 'Callback',{@SelectPV_DB_Type     ,f});
set(f.Main_Win.pushbutton_DB_PV_path              , 'Callback',{@SelectPV_DB          ,f});
% Callbacks for radiobuttons PV distrubution
set(f.Main_Win.radiobutton_input_dist_PV_list     , 'Callback',{@SelectPV_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_PV_random   , 'Callback',{@SelectPV_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_PV_DB_order , 'Callback',{@SelectPV_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_PV_sort     , 'Callback',{@SelectPV_dist_type   ,f});
set(f.Main_Win.radiobutton_input_dist_PV_manual   , 'Callback',{@SelectPV_dist_type   ,f});
set(f.Main_Win.pushbutton_dist_list_PV_path       , 'Callback',{@SelectPV_dist_list   ,f});
set(f.Main_Win.edit_dist_list_PV_path             , 'Callback',{@SelectPV_dist_list   ,f});
% Callbacks for general input data
set(f.Main_Win.popupmenu_ParrallelCom             , 'Callback',{@SelectParrallelCom   ,f});
% Callbacks for Output data
set(f.Main_Win.checkbox_output_active             , 'Callback',{@SetOutputActive      ,f});
set(f.Main_Win.checkbox_output_raw_only           , 'Callback',{@SetOutputRaw         ,f});
% set(f.Main_Win.pushbutton_generate_output         , 'Callback',{@Generate_Output      ,f});   % TODO -> Output
set(f.Main_Win.pushbutton_output_path_selection   , 'Callback',{@Select_Output_Path   ,f});
set(f.Main_Win.checkbox_output_path_filename      , 'Callback',{@Set_Output_filename  ,f});
% Callback for Simulation Start
set(f.Main_Win.pushbutton_start_PF                , 'Callback',{@Start_Simulation     ,f});

end

%% Body of callback functions

%% Callback SetOutputActive
% Enable/Disable some checkboxes in Output data
function SetOutputActive(~, ~, f)
if f.Main_Win.checkbox_output_active.Value == 0
    set_output_active(f,'off');
else
    set_output_active(f,'on' );
    if f.Main_Win.checkbox_output_raw_only.Value == 1   % If Raw only is on
        f.Main_Win.checkbox_output_data_selection_per_node_branch.Enable = 'off';
        f.Main_Win.checkbox_output_data_selection_per_unit       .Enable = 'off';
        f.Main_Win.checkbox_output_raw                           .Enable = 'off';
    end
end
end

%% Callback SetOutputRaw
% Enable/Disable some checkboxes in Output data
function SetOutputRaw(~, ~, f)
if f.Main_Win.checkbox_output_raw_only.Value == 1
    f.Main_Win.checkbox_output_data_selection_per_node_branch.Enable = 'off';
    f.Main_Win.checkbox_output_data_selection_per_unit       .Enable = 'off';
    f.Main_Win.checkbox_output_raw                           .Enable = 'off';
    f.Main_Win.checkbox_output_data_selection_per_node_branch.Value  = 0;
    f.Main_Win.checkbox_output_data_selection_per_unit       .Value  = 0;
    f.Main_Win.checkbox_output_raw                           .Value  = 1;
else
    f.Main_Win.checkbox_output_data_selection_per_node_branch.Enable = 'on';
    f.Main_Win.checkbox_output_data_selection_per_unit       .Enable = 'on';
    f.Main_Win.checkbox_output_raw                           .Enable = 'on';
    f.Main_Win.checkbox_output_data_selection_per_node_branch.Value  = 1;
    f.Main_Win.checkbox_output_data_selection_per_unit       .Value  = 1;
    f.Main_Win.checkbox_output_raw                           .Value  = 0;
end
end

%% Callback SelectGridPath
% Change path for grid selection and find out what grids occure in path
function SelectGridPath(~, ~, f)
Grid_Path = uigetdir(f.Main_Win.text_grid_path.String);
if Grid_Path ~= 0
    if Grid_Path(end) ~= '\'; Grid_Path = [Grid_Path,'\']; end
    f.Main_Win.text_grid_path.String = Grid_Path;
    f.Inputs.Grid_Path               = Grid_Path;
    fill_menu_grid_selection(f)
end
end

%% Callback SelectGrid
% Change default output filename if corresponding checkbox on
function SelectGrid(~, ~, f)
if f.Main_Win.checkbox_output_path_filename.Value == 1 % Default output path
    Name = ...
        f.Main_Win.popupmenu_grid_selection.String{...
        f.Main_Win.popupmenu_grid_selection.Value };
    if numel(Name) > 5 % '_empty' is a 1x6 char
        if strcmp(Name(end-5:end),'_empty') % Remove '_empty' from path
            f.Main_Win.edit_output_path_filename.String = Name(1:end-6);
        else
            f.Main_Win.edit_output_path_filename.String = Name;
        end
    else
        f.Main_Win.edit_output_path_filename.String = Name;
    end
end
end

%% Callback SelectLP_DB_Type
% Only if the radiobutton "Database" is clicked allow changing the LP type file
function SelectLP_DB_Type(~, ~, f)
if f.Main_Win.radiobutton_input_LP_DB.Value == 1
    f.Main_Win.pushbutton_DB_LP_path.Enable = 'on' ;
    f.Main_Win.edit_DB_LP_path      .Enable = 'on' ;
else
    f.Main_Win.pushbutton_DB_LP_path.Enable = 'off';
    f.Main_Win.edit_DB_LP_path      .Enable = 'off';
end
end

%% Callback SelectLP_DB
% Change the LP type file
function SelectLP_DB(~, ~, f)
[filename, path, ~] = uigetfile('*.mat','Select load profiles database',f.Inputs.LP_DB_Path);
if filename ~= 0; f.Main_Win.edit_DB_LP_path.String = [path, filename]; end
end

%% Callback SelectLP_dist_type
% Only if the radiobutton "Distribution List" or "Mean P" is clicked allow changing the LP distribution file
function SelectLP_dist_type(~, ~, f)
if f.Main_Win.radiobutton_input_dist_LP_list.Value == 1
    f.Main_Win.edit_dist_list_LP_path      .Enable = 'on' ;
    f.Main_Win.pushbutton_dist_list_LP_path.Enable = 'on' ;
else
    f.Main_Win.edit_dist_list_LP_path      .Enable = 'off';
    f.Main_Win.pushbutton_dist_list_LP_path.Enable = 'off';
end
end

%% Callback SelectLP_dist_list
% Change the LP distribution file
function SelectLP_dist_list(trigger_h, ~, f)
if trigger_h == f.Main_Win.pushbutton_dist_list_LP_path
    [filename, path, ~] = uigetfile('*.txt','Select Load distribution list', f.Inputs.LP_dist_path);
    if filename ~= 0
        f.Main_Win.edit_dist_list_LP_path.String = [path, filename];
    else
        fprintf('No Load Profile distribution list was chosen.\n');
    end
end
end

%% Callback SelectPV_DB_Type
% Only if the radiobutton "Database" is clicked allow changing the PV type file
function SelectPV_DB_Type(~, ~, f)
if f.Main_Win.radiobutton_input_PV_DB.Value == 1
    f.Main_Win.pushbutton_DB_PV_path.Enable = 'on' ;
    f.Main_Win.edit_DB_PV_path      .Enable = 'on' ;
else
    f.Main_Win.pushbutton_DB_PV_path.Enable = 'off';
    f.Main_Win.edit_DB_PV_path      .Enable = 'off';
end
end

%% Callback SelectPV_DB
% Change the PV type file
function SelectPV_DB(~, ~, f)
[filename, path, ~] = uigetfile('*.mat','Select PV profiles database', f.Inputs.PV_DB_Path);
if filename ~= 0; f.Main_Win.edit_DB_PV_path.String = [path, filename]; end
end

%% Callback SelectPV_dist_type
% Only if the radiobutton "Distribution List" is clicked allow changing the LP distribution file
function SelectPV_dist_type(~, ~, f)
if f.Main_Win.radiobutton_input_dist_PV_list.Value == 1
    f.Main_Win.edit_dist_list_PV_path      .Enable = 'on' ;
    f.Main_Win.pushbutton_dist_list_PV_path.Enable = 'on' ;
else
    f.Main_Win.edit_dist_list_PV_path      .Enable = 'off';
    f.Main_Win.pushbutton_dist_list_PV_path.Enable = 'off';
end
end

%% Callback SelectPV_dist_list
% Change the PV distribution file
function SelectPV_dist_list(trigger_h, ~, f)
if trigger_h == f.Main_Win.pushbutton_dist_list_PV_path
    [filename, path, ~] = uigetfile('*.txt','Select PV distribution list', f.Inputs.PV_dist_path);
    if filename ~= 0
        f.Main_Win.edit_dist_list_PV_path.String = [path, filename];
    else
        fprintf('No PV Profile distribution list was chosen.\n');
    end
end
end

%% Callback Select_Output_Path
% Change output path
function Select_Output_Path(~, ~, f)
Output_Path = uigetdir(f.Main_Win.text_output_path_selection.String);
if Output_Path ~= 0
    if Output_Path(end) ~= '\'; Output_Path = [Output_Path,'\']; end
    f.Main_Win.text_output_path_selection.String = Output_Path;
end
end

%% Callback Set_Output_filename
% Set or turn off default filename. If turn off any name can be set.
function Set_Output_filename(~, ~, f)
SelectGrid([],[],f)
if f.Main_Win.checkbox_output_path_filename.Value == 1 % Default output path
    f.Main_Win.edit_output_path_filename.Enable = 'off';
else
    f.Main_Win.edit_output_path_filename.Enable = 'on';
end
end

%% Callback Generate_Output (TODO: No function yet.)
% Open new GUI for defining the output files from the power flow results
function Generate_Output(~, ~, f) %#ok
LPC_Tool_GUI_Output(f);
end

%% Callback SelectParrallelCom
function SelectParrallelCom(~, ~, f)
if f.Main_Win.popupmenu_ParrallelCom.Value == 2     % If No Parrallel Com
    f.Main_Win.popupmenu_NumelCores.Value  = 1;
    f.Main_Win.popupmenu_NumelCores.Enable = 'off';
else
    f.Main_Win.popupmenu_NumelCores.Value  = f.max_num_Workers - 1;
    f.Main_Win.popupmenu_NumelCores.Enable = 'on';
end
end

%% Callback Start_Simulation
% Start the simulation
function Start_Simulation(~, ~, f)
% Set all parameters for simulation
f.Inputs.Grid_Path = f.Main_Win.text_grid_path.String;
f.Inputs.Grid_Name = f.Main_Win.popupmenu_grid_selection.String{f.Main_Win.popupmenu_grid_selection.Value};

% Set output options
f.Inputs.Output_option_preparation      = logical(f.Main_Win.checkbox_output_active                          .Value);
f.Inputs.Output_option_raw              = logical(f.Main_Win.checkbox_output_raw                             .Value);
f.Inputs.Output_option_raw_only         = logical(f.Main_Win.checkbox_output_raw_only                        .Value);
f.Inputs.Output_option_del_temp_files   = logical(f.Main_Win.checkbox_output_data_selection_delete_temp_files.Value);
f.Inputs.Output_option_per_node_branch  = logical(f.Main_Win.checkbox_output_data_selection_per_node_branch  .Value);
f.Inputs.Output_option_per_unit         = logical(f.Main_Win.checkbox_output_data_selection_per_unit         .Value);
f.Inputs.Output_option_Sin_Info         = logical(f.Main_Win.checkbox_output_data_selection_Sin_Info         .Value);
f.Inputs.Output_option_T_vector         = logical(f.Main_Win.checkbox_output_data_selection_T_Vector         .Value);
f.Inputs.Output_option_U                = logical(f.Main_Win.checkbox_output_data_selection_U                .Value);
f.Inputs.Output_option_P                = logical(f.Main_Win.checkbox_output_data_selection_P                .Value);
f.Inputs.Output_option_Q                = logical(f.Main_Win.checkbox_output_data_selection_Q                .Value);
f.Inputs.Output_option_S                = logical(f.Main_Win.checkbox_output_data_selection_S                .Value);
f.Inputs.Output_option_phi              = logical(f.Main_Win.checkbox_output_data_selection_Phi              .Value);
f.Inputs.Output_option_I                = logical(f.Main_Win.checkbox_output_data_selection_I                .Value);
f.Inputs.Output_option_P_flow           = logical(f.Main_Win.checkbox_output_data_selection_P_flow           .Value);
f.Inputs.Output_option_Q_flow           = logical(f.Main_Win.checkbox_output_data_selection_Q_flow           .Value);
f.Inputs.Output_option_S_flow           = logical(f.Main_Win.checkbox_output_data_selection_S_flow           .Value);

% Set load profiles type
if     f.Main_Win.radiobutton_input_LP_DB  	   .Value == 1; f.Inputs.LP_DB_Type = 'DB'      ;
elseif f.Main_Win.radiobutton_input_LP_LZR_Tool.Value == 1; f.Inputs.LP_DB_Type = 'LZR_Tool';
elseif f.Main_Win.radiobutton_input_LP_AAPD    .Value == 1; f.Inputs.LP_DB_Type = 'AAPD'    ;
end

% Set distribution type for load profiles
if     f.Main_Win.radiobutton_input_dist_LP_list    .Value == 1; f.Inputs.LP_dist_type = 'list'    ;
elseif f.Main_Win.radiobutton_input_dist_LP_random  .Value == 1; f.Inputs.LP_dist_type = 'random'  ;
elseif f.Main_Win.radiobutton_input_dist_LP_DB_order.Value == 1; f.Inputs.LP_dist_type = 'DB_order';
elseif f.Main_Win.radiobutton_input_dist_LP_sort    .Value == 1; f.Inputs.LP_dist_type = 'alphab'  ;
elseif f.Main_Win.radiobutton_input_dist_LP_manual  .Value == 1; f.Inputs.LP_dist_type = 'manual'  ;
end

% Set PV profiles type
if     f.Main_Win.radiobutton_input_PV_DB      .Value == 1; f.Inputs.PV_DB_Type = 'DB'      ;
elseif f.Main_Win.radiobutton_input_PV_LZR_Tool.Value == 1; f.Inputs.PV_DB_Type = 'LZR_Tool';
end

% Set distribution type for PV profiles
if     f.Main_Win.radiobutton_input_dist_PV_list    .Value == 1; f.Inputs.PV_dist_type = 'list'    ;
elseif f.Main_Win.radiobutton_input_dist_PV_random  .Value == 1; f.Inputs.PV_dist_type = 'random'  ;
elseif f.Main_Win.radiobutton_input_dist_PV_DB_order.Value == 1; f.Inputs.PV_dist_type = 'DB_order';
elseif f.Main_Win.radiobutton_input_dist_PV_sort    .Value == 1; f.Inputs.PV_dist_type = 'alphab'  ;
elseif f.Main_Win.radiobutton_input_dist_PV_manual  .Value == 1; f.Inputs.PV_dist_type = 'manual'  ;
end

% Set path and filename for load profiles database
if f.Main_Win.radiobutton_input_LP_DB.Value == 1
    [path, filename, ext] = fileparts(f.Main_Win.edit_DB_LP_path.String);
    if path(end) ~= '\'; path = [path,'\']; end
    f.Inputs.LP_DB_Path = path;
    f.Inputs.LP_DB_Name = [filename, ext];
end

% Set path and filename for PV profiles database
if f.Main_Win.radiobutton_input_PV_DB.Value == 1
    [path, filename, ext] = fileparts(f.Main_Win.edit_DB_PV_path.String);
    if path(end) ~= '\'; path = [path,'\']; end
    f.Inputs.PV_DB_Path = path;
    f.Inputs.PV_DB_Name = [filename, ext];
end

% Set path and filename for load distribution list
if f.Main_Win.radiobutton_input_dist_LP_list.Value == 1
    [path, filename, ext] = fileparts(f.Main_Win.edit_dist_list_LP_path.String);
    if path(end) ~= '\'; path = [path,'\']; end
    f.Inputs.LP_dist_path      = path;
    f.Inputs.LP_dist_list_name = [filename, ext];
end

% Set path and filename for PV distribution list
if f.Main_Win.radiobutton_input_dist_PV_list.Value == 1
    [path, filename, ext] = fileparts(f.Main_Win.edit_dist_list_PV_path.String);
    if path(end) ~= '\'; path = [path,'\']; end
    f.Inputs.PV_dist_path      = path;
    f.Inputs.PV_dist_list_name = [filename, ext];
end

% Set general input info
f.Inputs.VerSincal = str2double(f.Main_Win.edit_VerSincal.String);
if f.Main_Win.popupmenu_ParrallelCom.Value == 1
    f.Inputs.ParrallelCom = true ;
else
    f.Inputs.ParrallelCom = false;
end
if f.Inputs.ParrallelCom == true
    f.Inputs.NumelCores = str2double(...
        f.Main_Win.popupmenu_NumelCores.String{...
        f.Main_Win.popupmenu_NumelCores.Value});
else
    f.Inputs.NumelCores = 1;
end    

% Set Output path and filename
f.Inputs.Outputs_Path = f.Main_Win.text_output_path_selection.String;
if  f.Main_Win.checkbox_output_path_filename.Value == 0
    f.Inputs.Output_Name = f.Main_Win.edit_output_path_filename.String;
end

% Starting simulation with parameters
Mat2Sin_LPCalc(f.Inputs);

end

%% Function getGrid_List

function Grid_List = getGridList(Grid_Path)
Grid_List = struct2table(dir(Grid_Path));
[~,~,ext] = cellfun(@fileparts,Grid_List.name,'UniformOutput',false);
Grid_List.extension = ext;
Grid_List = Grid_List.name(~Grid_List.isdir & strcmp(Grid_List.extension,'.sin'));
Grid_List = strrep(Grid_List,'.sin','');
end

%% Function fill_menu_grid_selection

function fill_menu_grid_selection(f)
f.Inputs.Grid_List = getGridList(f.Inputs.Grid_Path);
f.Main_Win.popupmenu_grid_selection.Value = 1;
if size(f.Inputs.Grid_List, 1) == 0
    f.Main_Win.popupmenu_grid_selection.String = 'Current path contents no Sincal grids';
    f.Main_Win.popupmenu_grid_selection.Enable = 'off';
else
    f.Main_Win.popupmenu_grid_selection.String = f.Inputs.Grid_List;
    f.Main_Win.popupmenu_grid_selection.Enable = 'on';
    SelectGrid([],[],f)
end
end

%% Function set_output_active

function set_output_active(f, flag_input)
output_checkbox = {...
    'checkbox_output_raw_only'                          ,...
    'checkbox_output_raw'                               ,...
    'checkbox_output_data_selection_delete_temp_files'  ,...
    'checkbox_output_data_selection_U'                  ,...
    'checkbox_output_data_selection_P'                  ,...
    'checkbox_output_data_selection_Q'                  ,...
    'checkbox_output_data_selection_S'                  ,...
    'checkbox_output_data_selection_Phi'                ,...
    'checkbox_output_data_selection_I'                  ,...
    'checkbox_output_data_selection_P_flow'             ,...
    'checkbox_output_data_selection_Q_flow'             ,...
    'checkbox_output_data_selection_S_flow'             ,...
    'checkbox_output_data_selection_per_unit'           ,...
    'checkbox_output_data_selection_per_node_branch'    ,...
    };
for k_field = 1 : numel(output_checkbox)
    f.Main_Win.(output_checkbox{k_field}).Enable = flag_input;
end
% f.Main_Win.checkbox_output_data_selection_T_Vector    .Enable = flag_input; % TODO: No function yet!
% f.Main_Win.radiobutton_generate_nodes                 .Enable = flag_input; % TODO: Occur in GUI_Output
% f.Main_Win.radiobutton_generate_branches              .Enable = flag_input;
% f.Main_Win.radiobutton_generate_nodes_and_branches    .Enable = flag_input;
% f.Main_Win.pushbutton_generate_output                 .Enable = flag_input;
% f.Main_Win.pushbutton_generate_output_select_path     .Enable = flag_input;
end
